export const CARD_LEGALITIES = ['standard', 'expanded', 'unlimited'] as const;

export const CARD_RARITIES = [
  'ACE SPEC Rare',
  'Amazing Rare',
  'Classic Collection',
  'Common',
  'Double Rare',
  'Hyper Rare',
  'Illustration Rare',
  'LEGEND',
  'Promo',
  'Radiant Rare',
  'Rare',
  'Rare ACE',
  'Rare BREAK',
  'Rare Holo',
  'Rare Holo EX',
  'Rare Holo GX',
  'Rare Holo LV.X',
  'Rare Holo Star',
  'Rare Holo V',
  'Rare Holo VMAX',
  'Rare Holo VSTAR',
  'Rare Prime',
  'Rare Prism Star',
  'Rare Rainbow',
  'Rare Secret',
  'Rare Shining',
  'Rare Shiny',
  'Rare Shiny GX',
  'Rare Ultra',
  'Shiny Rare',
  'Shiny Ultra Rare',
  'Special Illustration Rare',
  'Trainer Gallery Rare Holo',
  'Ultra Rare',
  'Uncommon',
] as const;

export const CARD_SUBTYPES = [
  'ACE SPEC',
  'Ancient',
  'BREAK',
  'Baby',
  'Basic',
  'EX',
  'Eternamax',
  'Fusion Strike',
  'Future',
  'GX',
  'Goldenrod Game Corner',
  'Item',
  'LEGEND',
  'Level-Up',
  'MEGA',
  'Pokémon Tool',
  'Pokémon Tool F',
  'Prime',
  'Prism Star',
  'Radiant',
  'Rapid Strike',
  'Restored',
  "Rocket's Secret Machine",
  'SP',
  'Single Strike',
  'Special',
  'Stadium',
  'Stage 1',
  'Stage 2',
  'Star',
  'Supporter',
  'TAG TEAM',
  'Team Plasma',
  'Technical Machine',
  'Tera',
  'Ultra Beast',
  'V',
  'V-UNION',
  'VMAX',
  'VSTAR',
  'ex',
] as const;

export const CARD_TYPES = [
  'Colorless',
  'Darkness',
  'Dragon',
  'Fairy',
  'Fighting',
  'Fire',
  'Grass',
  'Lightning',
  'Metal',
  'Psychic',
  'Water',
] as const;

export const CARD_SUPERTYPES = ['Energy', 'Pokémon', 'Trainer'] as const;
